// Centralized environment variable handling
export const env = {
  NEXT_PUBLIC_MATRIX_HOMESERVER_URL: process.env.NEXT_PUBLIC_MATRIX_HOMESERVER_URL,
  NEXT_PUBLIC_MELO_PRIVATE_MODE: process.env.NEXT_PUBLIC_MELO_PRIVATE_MODE,
  NEXT_PUBLIC_MATRIX_INVITE_REQUIRED: process.env.NEXT_PUBLIC_MATRIX_INVITE_REQUIRED,
};